# Generated by Django 4.1.7 on 2023-04-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_sell_indicator', models.CharField(help_text='A value of BUY for buys, SELL for sells.', max_length=4)),
                ('price', models.FloatField(help_text='The price of the Trade.')),
                ('quantity', models.IntegerField(help_text='The amount of units traded.')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(blank=True, help_text='The asset class of the instrument traded. E.g. Bond, Equity, FX...etc', max_length=255, null=True)),
                ('counterparty', models.CharField(blank=True, help_text='The counterparty the trade was executed with. May not always be available', max_length=255, null=True)),
                ('instrument_id', models.CharField(help_text='The ISIN/ID of the instrument traded. E.g. TSLA, AAPL, AMZN...etc', max_length=255)),
                ('instrument_name', models.CharField(help_text='The name of the instrument traded.', max_length=255)),
                ('trade_date_time', models.DateTimeField(help_text='The date-time the Trade was executed')),
                ('trade_id', models.CharField(blank=True, help_text='The unique ID of the trade', max_length=255, null=True)),
                ('trader', models.CharField(help_text='The name of the Trader', max_length=255)),
                ('trade_details', models.ForeignKey(help_text='The details of the trade, i.e. price, quantity', on_delete=django.db.models.deletion.CASCADE, to='core.tradedetails')),
            ],
        ),
    ]
