# Generated by Django 4.1.7 on 2023-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(blank=True, choices=[('Bond', 'BOND'), ('Equity', 'EQUITY'), ('fx', 'FIXED DEPOSIT')], help_text='The asset class of the instrument traded. E.g. Bond, Equity, FX...etc', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument_id',
            field=models.CharField(choices=[('amazon', 'AMZN'), ('tesla', 'TSLA'), ('alibaba', 'ALBAB'), ('apple', 'APPL')], help_text='The ISIN/ID of the instrument traded. E.g. TSLA, AAPL, AMZN...etc', max_length=255),
        ),
    ]
